main/urls.py
from django.views.generic.simple import redirect_to

import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Health check endpoint.  Used by AWS load balancer.  Want something stable that
    # won't be redirected or change
    url(r'^_health$', 'c2g.views.healthcheck'),
                       
    # Testing the error pages (404 and 500)
    url(r'^_throw500$', 'c2g.views.throw500'),
    url(r'^_throw404$', 'c2g.views.throw404'),

    #Testing messages
    url(r'^_test_messages$', 'c2g.views.test_messages'),

    url(r'^honor_code$', 'c2g.views.hc'),
    url(r'^terms_of_service$', 'c2g.views.tos'),
    url(r'^privacy$', 'c2g.views.privacy'),
    url(r'^contactus$', 'c2g.views.contactus'),
    url(r'^faq$', 'c2g.views.faq'),
    url(r'^test_xml$', 'courses.exams.views.show_test_xml'),
    url(r'^hiring/?$', 'courses.landing.views.hiring'),

    url(r'^maint$', 'c2g.views.maintenance'),

    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/unenroll/?$', 'courses.views.unenroll'),

    # general exam stuff--These endpoints are hidden from student users and do not have to be named (i.e. aliased for each exam subtype)
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/create/?$', 'courses.exams.views.create_exam'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/save/?$', 'courses.exams.views.save_exam_ajax'),
    url(r'^delete_exam/?', 'courses.exams.actions.delete_exam'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/check_metadata_xml/?$', 'courses.exams.views.check_metadata_xml'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/edit/?$', 'courses.exams.views.edit_exam'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/save/?$', 'courses.exams.views.edit_exam_ajax_wrapper', name='save_edited_exam'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/submit/?$', 'courses.exams.views.collect_data'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/all_submissions_to_grade/?$', 'courses.exams.views.view_submissions_to_grade'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/post_csv_grades/?$', 'courses.exams.views.post_csv_grades'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/get_csv_grades/?$', 'courses.exams.views.view_csv_grades'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/save_student_progress/?$', 'courses.exams.views.student_save_progress'),

    #The rest of these URLs end up in the location bar of student users.  We should alias them for each exam subtype so that students do not get
    #confused.  Would love to make this DRY, because it's very repetitive, but I don't know how.
                      
    #Exam subtype of exam
    #All subtypes use the same views in this list, so any reversing should be done using the name, i.e. 'exam_list', otherwise it
    #will not return the right URL for the right type
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/?$', 'courses.exams.views.listAll', {'show_types':['exam',]}, name='exam_list'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/?$', 'courses.exams.views.show_exam', name='exam_show'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/snapshot/?$', 'courses.exams.views.show_populated_exam', name='exam_populated'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/graded/?$', 'courses.exams.views.show_graded_exam', name='exam_graded'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/view_submissions/?$', 'courses.exams.views.view_my_submissions', name='exam_my_submissions'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/record/(?P<record_id>[0-9]+)/?$', 'courses.exams.views.show_graded_record', name='exam_record'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/exams/(?P<exam_slug>[a-zA-Z0-9_-]+)/feedback/?$', 'courses.exams.views.exam_feedback'),

    #problemset subtype of exam
    #This and the exams list use the same view, so any reversing should be done using the name, i.e. 'survey_list', otherwise it
    #will be always return /exams/
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/problemsets/?$', 'courses.exams.views.listAll', {'show_types':['problemset',]}, name='problemset_list'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/problemsets/(?P<exam_slug>[a-zA-Z0-9_-]+)/?$', 'courses.exams.views.show_exam', name='problemset_show'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/problemsets/(?P<exam_slug>[a-zA-Z0-9_-]+)/snapshot/?$', 'courses.exams.views.show_populated_exam', name='problemset_populated'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/problemsets/(?P<exam_slug>[a-zA-Z0-9_-]+)/graded/?$', 'courses.exams.views.show_graded_exam', name='problemset_graded'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/problemsets/(?P<exam_slug>[a-zA-Z0-9_-]+)/view_submissions/?$', 'courses.exams.views.view_my_submissions', name='problemset_my_submissions'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/problemsets/(?P<exam_slug>[a-zA-Z0-9_-]+)/record/(?P<record_id>[0-9]+)/?$', 'courses.exams.views.show_graded_record', name='problemset_record'),

    #survey subtype of exam
    #This and the exams list use the same view, so any reversing should be done using the name, i.e. 'survey_list', otherwise it
    #will be always return /exams/
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/surveys/?$', 'courses.exams.views.listAll', {'show_types':['survey',]}, name='survey_list'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/surveys/(?P<exam_slug>[a-zA-Z0-9_-]+)/?$', 'courses.exams.views.show_exam', name='survey_show'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/surveys/(?P<exam_slug>[a-zA-Z0-9_-]+)/snapshot/?$', 'courses.exams.views.show_populated_exam', name='survey_populated'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/surveys/(?P<exam_slug>[a-zA-Z0-9_-]+)/graded/?$', 'courses.exams.views.show_graded_exam', name='surveys_graded'), #admittedly doesn't make sense, here for consistency
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/surveys/(?P<exam_slug>[a-zA-Z0-9_-]+)/view_submissions/?$', 'courses.exams.views.view_my_submissions', name='survey_my_submissions'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/surveys/(?P<exam_slug>[a-zA-Z0-9_-]+)/record/(?P<record_id>[0-9]+)/?$', 'courses.exams.views.show_graded_record', name='survey_record'),

    #interactive_exercise subtype of exam
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/interactive_exercises/?$', 'courses.exams.views.listAll', {'show_types':['interactive_exercise',]}, name='interactive_exercise_list'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/interactive_exercises/(?P<exam_slug>[a-zA-Z0-9_-]+)/?$', 'courses.exams.views.show_exam', name='interactive_exercise_show'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/interactive_exercises/(?P<exam_slug>[a-zA-Z0-9_-]+)/snapshot/?$', 'courses.exams.views.show_populated_exam', name='interactive_exercise_populated'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/interactive_exercises/(?P<exam_slug>[a-zA-Z0-9_-]+)/graded/?$', 'courses.exams.views.show_graded_exam', name='interactive_exercise_graded'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/interactive_exercises/(?P<exam_slug>[a-zA-Z0-9_-]+)/view_submissions/?$', 'courses.exams.views.view_my_submissions', name='interactive_exercise_my_submissions'),
    url(r'^(?P<course_prefix>[a-zA-Z0-9_-]+)/(?P<course_suffix>[a-zA-Z0-9_-]+)/interactive_exercises/(?P<exam_slug>[a-zA-Z0-9_-]+)/record/(?P<record_id>[0-9]+)/?$', 'courses.exams.views.show_graded_record', name='interactive_exercise_record'),

    #emailoptout
    url(r'^email_optout/(?P<code>[a-zA-Z0-9]+)/?$', 'courses.email_members.views.optout', name='maillist_optout'),
    
    # Commented out the following 2 urls since point to a signup page which is
    # no longer required.
#    url(r'^courses/?$', 'c2g.views.home', name='c2g_home'),
#    url(r'^courses/signup/?$', 'courses.actions.signup'),

#    url(r'^class2go/', include('class2go.foo.urls')),
   
    #shibboleth login
    url(r'^shib-login/?$', 'accounts.views.shib_login', name='shib_login'),
                       
    
    #impersonate
    url(r'^impersonate/(?P<username>[\w.@+-]+)/?$', 'accounts.views.impersonate', name='impersonate'),
                       
    #for data collection
    url(r'^videos/save/', 'courses.videos.actions.save_video_progress'),
    url(r'^videos/record_download/', 'courses.videos.actions.record_download'),
    url(r'^problemsets/attempt/(?P<problemId>\d+)/?$', 'problemsets.views.attempt'),

main/courses/forms.py
from django import forms

class LiveDateForm(forms.Form):
    live_datetime = forms.DateTimeField(required=False, widget=forms.widgets.DateTimeInput(format='%m/%d/%Y %H:%M', attrs={'data-datetimepicker':''}))

main/courses/videos/forms.py
from django import forms
from c2g.models import ContentSection, Video, Exercise, Course
# import the logging library
#import logging
#logger = logging.getLogger('django')

import gdata.youtube.service

class S3UploadForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        #logger.warning('test')
        course = kwargs.pop('course')
        super(S3UploadForm, self).__init__(*args, **kwargs)
        self.fields['section'] = forms.ModelChoiceField(ContentSection.objects.filter(course=course, is_deleted=False), empty_label=None)
        instance = getattr(self, 'instance', None)
        if instance and instance.id:
            del self.fields['file']
        else:
            self.fields['file'].help_text = "Select the mp4 video file on your machine to upload - you need to do this even if the file is already on YouTube so that we can provide downloads and generate a thumbnail index."
        self.fields['slug'].help_text = "A unique identifier that will be shown in the URL"
    
    def clean_url(self):
        url = self.cleaned_data['url']
        if url:
            yt_service = gdata.youtube.service.YouTubeService()
            try:
                entry = yt_service.GetYouTubeVideoEntry(video_id=url)
                self.instance.duration = entry.media.duration.seconds
            except gdata.service.RequestError:
                raise forms.ValidationError('Invalid YouTube video ID.')
        return url

    class Meta:
        model = Video
        fields = ('title', 'slug', 'section', 'description', 'file', 'url', 'live_datetime')
        widgets = {
            'live_datetime': forms.widgets.DateTimeInput(format='%m/%d/%Y %H:%M', attrs={'data-datetimepicker':''})
        }

class ManageExercisesForm(forms.Form):
    file = forms.FileField()
    video_time = forms.IntegerField(min_value=0)
    course = forms.CharField(widget=(forms.HiddenInput()))

class AdditionalExercisesForm(forms.Form):
    def __init__(self, *args, **kwargs):
        used_exercises = kwargs.pop('used_exercises', None)
        super(AdditionalExercisesForm, self).__init__(*args, **kwargs)
        self.fields['exercise'] = forms.ModelMultipleChoiceField(used_exercises)
#        for used_exercise in used_exercises:
#            check = 'check' + str(used_exercise.id)
#            video_time = 'time' + str(used_exercise.id)
#            self.fields[check] = forms.BooleanField(required=False)
#            self.fields[video_time] = forms.IntegerField(required=False)

    def clean(self):
        cleaned_data = super(AdditionalExercisesForm, self).clean()
        check = cleaned_data.get('check')
        poo = cleaned_data.get('poo')
        if check and not poo:
            self._errors['poo'] = self.error_class(['Dont be so poopy'])
        return cleaned_data

class ReorderExercisesForm(forms.Form):
    def __init__(self, *args, **kwargs):
        current_exercises = kwargs.pop('current_exercises', None)
        super(ReorderExercisesForm, self).__init__(*args, **kwargs)
        for current_exercise in current_exercises:
            self.fields[current_exercise.exercise.fileName] = forms.IntegerField(initial=current_exercise.video_time)

main/templates/videos/draft/delete_video_form.html
<form name="delete_video_form" action="{% url 'courses.videos.actions.delete_video' %}" method="POST">    <input type="hidden" name="video_id" id="delete_video_id" />    <input type="hidden" name="course_prefix" value="{{ common_page_data.course_prefix }}" />    <input type="hidden" name="course_suffix" value="{{ common_page_data.course_suffix }}" />    {% csrf_token %}</form><script type="text/javascript">    function DeleteVideo(id) {        if (confirm("Are you sure you want to delete the video '" + $("#video_"+id+"_title").html() + "'?")) {            $("#delete_video_id").val(id);            document.forms.delete_video_form.submit();        }    }</script>

main/templates/videos/draft/list.html
{% extends "course_base.html" %}
{% block title %}Videos | {{common_page_data.course.title}}{% endblock %}
{% block videos_link_class %}class="active"{% endblock videos_link_class %}

{% block course_page_title %}Videos (<a href="{% url 'courses.views.main' common_page_data.course_prefix common_page_data.course_suffix %}">{{common_page_data.course.title}}</a>){% endblock course_page_title %}

{% block m_column_content %}
<div id="c2g_layout_m_column" class="span12">
    {% include "draft/item_checkbox_functions.html" %}
    {% include "videos/draft/video_management_section.html" %}

    {% for section_structure in section_structures %}
    <div class="well">
        {% include "content_sections/draft/section.html" %}
    </div>
    {% empty %}
        <p style='margin: 20px;'>No videos have been added to this section.</p>
    {% endfor %}
</div>
{% endblock m_column_content %}

{% block addl_scripts %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/core/bootstrap-datepicker.js"></script>
    <script type="text/javascript">$(".datepicker").datepicker();</script>
    {% include "controls/tinymce.html" %}
{% endblock addl_scripts %}

main/templates/videos/draft/video_list_item.html
<table style="width:100%">
    <tr id="video_{{item.video.id}}">
        <td width="20" align="middle"><input type="checkbox" name="video_{{item.video.id}}" id="video_{{item.video.id}}" class="item_selector section_{{item.video.section.id}}_item_selector" /></td>
        <td><em class="icon-facetime-video" style="font-size:16px;opacity:.3;"></em> <h4 style="margin-top:10px;display:inline;"><a id="video_{{item.video.id}}_title" href="{% url 'courses.videos.views.view' common_page_data.course_prefix common_page_data.course_suffix item.video.slug %}">{{item.video.title}}</a>{% if item.video.url %} <a data-c2g-tooltip title="Audience retention report - you must be logged into the correct YT account to use" href="{{item.video.ret_url}}" target="_blank">&nbsp;<em class="icon-dashboard"></em></a>{% endif %}</h4></td>
        <td width="240">
            {% if item.video.is_synced %}
            <div style="color: #00A000; padding: 0px;">
                <em class="icon-ok" style="font-size:17px"></em> Draft=Ready
            </div>
            {% else %}
            <div style="color: #A07000; padding: 0px;">
                <em class="icon-random" style="font-size:17px"></em> Draft Different From Ready
            </div>
            {% endif %}
        </td>
        <td width="70">
            {% autoescape off %}{{ item.visible_status }}{% endautoescape %}
        </td>
    	<td width="60">
    	    <a href="{% url 'courses.videos.views.edit' common_page_data.course_prefix common_page_data.course_suffix item.video.slug %}">Edit</a>
    	</td>
        <td width="140">
        </td>
        <td width="20">
            <a href="javascript:DeleteVideo('{{item.video.id}}')" style="float: right; font-size: 12pt; font-weight: bold; color: rgb(150,150,150);margin-right: 10px;">x</a>
        </td>
    </tr>
</table>

main/templates/videos/draft/video_management_section.html
<div class="container-fluid">
    <a href="javascript:selectAll()">Select all</a> / <a href="javascript:unselectAll()">Unselect all</a>
    <div style="width:700px; float: right;margin-left: 20px;">
        <form name="commit_form" action="{% url 'courses.actions.commit' %}" method="POST">
            <input type="hidden" id="commit_ids" name="commit_ids" value="" />
            <input type="button" value="Make Ready" class="btn" style='width: 150px; margin-right: 10px;' onclick="commit_clicked()"/>Copy the draft version of selected items to ready
            <input type="hidden" name="course_prefix" value="{{ common_page_data.course_prefix }}" />
            <input type="hidden" name="course_suffix" value="{{ common_page_data.course_suffix }}" />
            {% csrf_token %}
        </form>
        <script type="text/javascript">
        function commit_clicked() {
            document.getElementById("commit_ids").value = getCheckedIds();
            if (document.getElementById("commit_ids").value == '') {
                alert('Nothing selected to commit.');
                return;
            }
            document.forms.commit_form.submit();
        }        
        </script>
        <form name="revert_form" action="{% url 'courses.actions.revert' %}" method="POST">
            <input type="hidden" id="revert_ids" name="revert_ids" value="" />
            <input type="button" value="Reset to Ready" class="btn" style='width: 150px; margin-right: 10px;' onclick="revert_clicked()"/>Reset the draft version of selected items back to ready
            <input type="hidden" name="course_prefix" value="{{ common_page_data.course_prefix }}" />
            <input type="hidden" name="course_suffix" value="{{ common_page_data.course_suffix }}" />
            {% csrf_token %}
        </form>
        <script type="text/javascript">
        function revert_clicked() {
            document.getElementById("revert_ids").value = getCheckedIds();
            if (document.getElementById("revert_ids").value == '') {
                alert('Nothing selected to reset.');
                return;
            }
            
            r = confirm("Resetting any item will cause any changes to the draft version to be discarded. Are you sure you want to reset all of the selected items?")
            if (!r) return;
            
            document.forms.revert_form.submit();
        }
        </script>
        <form name="change_live_datetime_form" action="{% url 'courses.actions.change_live_datetime' %}" method="POST" onsubmit="return apply_clicked()">
            <input type="hidden" id="change_live_datetime_ids" name="change_live_datetime_ids" value="" />
	    <input type="submit" name="action" value="Make Ready and Go Live" class="btn" style='margin-bottom: 9px' onclick="clicked=this.value"/>
            <label for="id_live_datetime" style="display:inline">or go live</label>
	    {{ form.live_datetime }}
            <input type="submit" name="action" value="Set Live Date" class="btn" style='margin: 0 0 9px 0' onclick="clicked=this.value"/>
	    or
	    <input type="submit" name="action" value="Remove Live Date" class="btn" style='margin: 0 0 9px 0' onclick="clicked=this.value"/>
            {{ form.live_datetime.errors }}
            <input type="hidden" name="course_prefix" value="{{ common_page_data.course_prefix }}" />
            <input type="hidden" name="course_suffix" value="{{ common_page_data.course_suffix }}" />
	    <input type="hidden" name="list_type" value="videos" />
            {% csrf_token %}
        </form>
        <script type="text/javascript">
	var clicked;
        function apply_clicked() {
            document.getElementById("change_live_datetime_ids").value = getCheckedIds();
            if (document.getElementById("change_live_datetime_ids").value == '') {
	        if (clicked == "Make Ready and Go Live") {
                    alert('Nothing selected to make ready and go live.');
	        }
	        else if (clicked == "Set Live Date") {
	            alert('Nothing selected to set the live date for.');
	        }
	        else {
	            alert('Nothing selected to remove the live date for.');
                }
                return false;
            }
	    return true;
        }
        </script>
        
        {% block addl_content_management_content %}{% endblock addl_content_management_content %}
    </div>
    <label class="pull-right"><strong>With selected:</strong></label>
</div>
<script type="text/javascript">
function getCheckedIds() {
    all_inputs = document.getElementsByTagName('input');
    is_first = true;
    id_str = '';
    for (var i = 0; i < all_inputs.length; i++) {
        input = all_inputs[i];
        if (input.hasAttribute('type') && input.getAttribute('type') == 'checkbox' && input.checked) {
            if (is_first) {
                is_first = false;
            } else {
                id_str += ',';
            }
            id_str += input.id;
        }
    }
    return id_str;
}
</script>
<div class="well tight" style="overflow:hidden;">
    <div class="pull-left">
        <input type="button" value="New section" onclick="$('#new_section_form').toggle();" class="btn" style="margin-left: 20px;" />
        <a class="btn" style="margin-left: 5px;" href="{% url 'courses.content_sections.views.reorder' common_page_data.course_prefix common_page_data.course_suffix %}">Re-order Sections</a>
        <a class="btn btn-primary" style="margin-left: 30px;" href="{% url 'courses.videos.views.upload' common_page_data.course_prefix common_page_data.course_suffix %}">New Video</a>
    </div>
    <div class="pull-right" id="new_section_form" style="display:none;padding-right:15px;">
        <form action="{% url 'courses.actions.add_section' %}" method="POST" class="form-inline" style="margin-bottom:0;">
            <div class="control-group" style="margin:0;">
                <label class="control-label">Title for new section</label>
                <input name="title" id="title" type="text" />
                <input type="submit" value="Create" class="btn" />
                <input type="hidden" name="course_prefix" value="{{ common_page_data.course_prefix }}" />
                <input type="hidden" name="course_suffix" value="{{ common_page_data.course_suffix }}" />
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

{% include "videos/draft/delete_video_form.html" %}
{% include "content_sections/draft/delete_content_section_form.html" %}